const express = require('express');
const userController = require('../controller/user_view');
const router = express.Router();

router.get('/all', userController.getAllUsers);
router.get('/ict-admin/all', userController.getICT_administrators);
router.get('/ict-admin/:id/get', userController.getICT_administrator);
router.post('/ict-admin/create', userController.createICT_administrator);
router.put('/ict-admin/update', userController.updateICT_administrator);
router.delete('/ict-admin/delete', userController.deleteICT_administrator);
router.get('/all', userController.getAuditors);
router.get('/auditor/:id/get', userController.getAuditor);
router.post('/auditor/create', userController.createAuditor);
router.put('/auditor/update', userController.updateAuditor);
router.delete('/auditor/delete', userController.deleteAuditor);
router.get('/all', userController.getProprietors);
router.get('/proprietor/:id/get', userController.getProprietor);
router.post('/proprietor/create', userController.createProprietor);
router.put('/proprietor/update', userController.updateProprietor);
router.delete('/proprietor/delete', userController.deleteProprietor);
router.get('/all', userController.getPrincipals);
router.get('/principal/:id/get', userController.getPrincipal);
router.post('/principal/create', userController.createPrincipal);
router.put('/principal/update', userController.updatePrincipal);
router.delete('/principal/delete', userController.deletePrincipal);
router.get('/all', userController.getHeadteachers);
router.get('/headteacher/:id/get', userController.getHeadteacher);
router.post('/headteacher/create', userController.createHeadteacher);
router.put('/headteacher/update', userController.updateHeadteacher);
router.delete('/headteacher/delete', userController.deleteHeadteacher);
router.get('/all', userController.getBursars);
router.get('/bursar/:id/get', userController.getBursar);
router.post('/bursar/create', userController.createBursar);
router.put('/bursar/update', userController.updateBursar);
router.delete('/bursar/delete', userController.deleteBursar);
router.get('/students/all', userController.getStudents);
router.get('/students/get', userController.getStudentsInParticularSchool);
router.get('/student/:id/get', userController.getStudent);
router.post('/student/create', userController.createStudent);
router.put('/student/update', userController.updateStudent);
router.delete('/student/delete', userController.deleteStudent);
router.get('/all', userController.getParents);
router.get('/parent/get', userController.getParentsInParticularSchool);
router.get('/parent/:id/get', userController.getParent);
router.post('/parent/create', userController.createParent);
router.put('/parent/update', userController.updateParent);
router.delete('/parent/delete', userController.deleteParent);

module.exports = router;